### ISSUE TITLE
Server thinks blocks remain after Rocket Launch blows up ground.

### ISSUE THREAD

**Issue by maddmaam** [gummy77/Creeper-Space-Program#1]
As described, easiest to reproduce when you launch rocket on soft surface like sand or dirt. Server will think blocks under rocket is still there, and will band the player back and forward.

**Comment by gummy77** [comment]
I believe its because explosions are being summoned on the client through the packet response, will look into changing that

**Comment by gummy77** [comment]
resolved with [this push](https://github.com/gummy77/Creeper-Space-Program/commit/c38a895e219fd95665c20d457f3ec813c03fda68)
